# fly.toml app configuration file generated for beemoo-server on 2025-08-12T01:24:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beemoo-server'
primary_region = 'fra'

[build]

[env]
  CLIENT_URL = 'https://beemoo.vercel.app'
  PORT = '3000'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
